name: main
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.x"

      - run: pip install pre-commit-mirror-maker

      - name: set git config
        run: |
          git config user.name 'Github Actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - run: pre-commit-mirror --language node --package-name pyright --entry pyright --types python .

      - run: ./scripts/update-readme.sh

      - run: git push origin HEAD:refs/heads/main --tags
